
import { Objective, Profile, Gender, Mood } from './types';

export const APP_ID = 'velum-v1';

export const TRAVEL_CITIES = [
  'João Pessoa', 'Campina Grande', 'Patos', 'Recife', 'Natal', 'Pipa', 'Maceió', 'Fortaleza', 'Salvador'
];

export const OPTIONS = {
  genders: Object.values(Gender),
  appearance: ['Minimalista', 'Alternativo', 'Clássico', 'Dark', 'Executivo', 'Casual Chic'],
  traits: ['Tatuagens', 'Piercings', 'Barba', 'Cabelos Coloridos', 'Olhar Marcante', 'Sorriso Enigmático'],
  drinks: ['Vinho Tinto', 'Whiskey Single Malt', 'Gin tônica', 'Coquetel Autoral', 'Champagne', 'Saquê'],
  music: ['Deep House', 'Techno', 'Jazz/Blues', 'Rock Alternativo', 'Indie', 'MPB', 'Eletrônica'],
  hardLimits: ['Desrespeito', 'Falta de Higiene', 'Pressão', 'Registro não autorizado']
};

export const MOCK_USER: Profile = {
  uid: 'me',
  username: 'alex_noir',
  email: 'alex@noir.com',
  name: 'Alex',
  age: 28,
  gender: Gender.HOMEM,
  seeking: [Gender.MULHER, Gender.CASAL_MF],
  bio: 'Explorador do estilo de vida liberal.',
  objectives: [Objective.MENAGE],
  mood: Mood.ENCONTRO,
  isPrivate: true,
  photos: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600'],
  location: { lat: -7.1195, lng: -34.8450, city: 'João Pessoa', state: 'Paraíba', type: 'GPS' },
  vaultPhotos: [],
  interests: ['Arte'],
  appearance: 'Minimalista'
};

export const MOCK_PROFILES: Profile[] = [
  {
    uid: '1',
    username: 'julia_jp',
    email: 'julia@example.com',
    name: 'Júlia',
    age: 32,
    gender: Gender.MULHER,
    seeking: [Gender.HOMEM],
    bio: 'Discreta e decidida.',
    objectives: [Objective.CASUAL_HOJE],
    mood: Mood.ENCONTRO,
    isPrivate: true,
    photos: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -7.1195, lng: -34.8450, city: 'João Pessoa', state: 'PB', type: 'GPS' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '2',
    username: 'pablo_pipa',
    email: 'pablo@pipa.com',
    name: 'Pablo',
    age: 27,
    gender: Gender.HOMEM,
    seeking: [Gender.MULHER],
    bio: 'Aproveitando o melhor de Pipa.',
    objectives: [Objective.SOLO],
    mood: Mood.FESTA,
    isPrivate: false,
    photos: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -6.2306, lng: -35.0486, city: 'Pipa', state: 'RN', type: 'MANUAL' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '3',
    username: 'couple_natal',
    email: 'couple@natal.com',
    name: 'Bia & Leo',
    age: 35,
    gender: Gender.CASAL_MF,
    seeking: [Gender.MULHER, Gender.CASAL_MF],
    bio: 'Casal liberal em Natal.',
    objectives: [Objective.TROCA_DE_CASAL],
    mood: Mood.DISCRETO,
    isPrivate: true,
    photos: ['https://images.unsplash.com/photo-1516051662687-567d7c4e8f6a?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -5.7945, lng: -35.2110, city: 'Natal', state: 'RN', type: 'MANUAL' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '4',
    username: 'recife_noir',
    email: 'recife@noir.com',
    name: 'Clara',
    age: 29,
    gender: Gender.MULHER,
    seeking: [Gender.HOMEM, Gender.MULHER],
    bio: 'Artes e prazer em Recife.',
    objectives: [Objective.MENAGE],
    mood: Mood.CONVERSA,
    isPrivate: false,
    photos: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -8.0476, lng: -34.8770, city: 'Recife', state: 'PE', type: 'MANUAL' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '5',
    username: 'cg_guy',
    email: 'cg@guy.com',
    name: 'Ricardo',
    age: 31,
    gender: Gender.HOMEM,
    seeking: [Gender.MULHER],
    bio: 'Executivo em Campina.',
    objectives: [Objective.CASUAL_HOJE],
    mood: Mood.DISCRETO,
    isPrivate: true,
    photos: ['https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -7.2245, lng: -35.8761, city: 'Campina Grande', state: 'PB', type: 'MANUAL' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '6',
    username: 'susi_natal',
    email: 'susi@natal.com',
    name: 'Susi',
    age: 24,
    gender: Gender.MULHER,
    seeking: [Gender.HOMEM, Gender.CASAL_MF],
    bio: 'Curiosa por novas experiências.',
    objectives: [Objective.CURIOSO],
    mood: Mood.FESTA,
    isPrivate: false,
    photos: ['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -5.7945, lng: -35.2110, city: 'Natal', state: 'RN', type: 'MANUAL' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '7',
    username: 'couple_recife',
    email: 'couple@recife.com',
    name: 'Fernanda & Edu',
    age: 40,
    gender: Gender.CASAL_MF,
    seeking: [Gender.CASAL_MF],
    bio: 'Apenas troca de casais.',
    objectives: [Objective.TROCA_DE_CASAL],
    mood: Mood.DISCRETO,
    isPrivate: true,
    photos: ['https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -8.0476, lng: -34.8770, city: 'Recife', state: 'PE', type: 'MANUAL' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '8',
    username: 'pipa_vibes',
    email: 'pipa@vibes.com',
    name: 'Luna',
    age: 26,
    gender: Gender.TRANS_NB,
    seeking: [Gender.HOMEM, Gender.MULHER],
    bio: 'Livre em Pipa.',
    objectives: [Objective.CASUAL_HOJE],
    mood: Mood.ENCONTRO,
    isPrivate: false,
    photos: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -6.2306, lng: -35.0486, city: 'Pipa', state: 'RN', type: 'MANUAL' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '9',
    username: 'cg_curious',
    email: 'cg@curious.com',
    name: 'Mateus',
    age: 23,
    gender: Gender.HOMEM,
    seeking: [Gender.CASAL_MF],
    bio: 'Terceiro disponível.',
    objectives: [Objective.MENAGE],
    mood: Mood.ENCONTRO,
    isPrivate: false,
    photos: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -7.2245, lng: -35.8761, city: 'Campina Grande', state: 'PB', type: 'MANUAL' },
    vaultPhotos: [],
    interests: []
  },
  {
    uid: '10',
    username: 'jp_couple_new',
    email: 'jp@couple.com',
    name: 'Ana & Caio',
    age: 28,
    gender: Gender.CASAL_MF,
    seeking: [Gender.HOMEM, Gender.MULHER],
    bio: 'Primeira vez no app.',
    objectives: [Objective.CURIOSO],
    mood: Mood.CONVERSA,
    isPrivate: true,
    photos: ['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=600'],
    location: { lat: -7.1195, lng: -34.8450, city: 'João Pessoa', state: 'PB', type: 'GPS' },
    vaultPhotos: [],
    interests: []
  }
];
